apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: first-ml:/Pod:asif-test/model-debug
    cni.projectcalico.org/containerID: 9dd35e91b3e0a472fc400fba9439eea6866c1faeaf6f422e77c1dbc69c3c8727
    cni.projectcalico.org/podIP: 10.96.3.67/32
    cni.projectcalico.org/podIPs: 10.96.3.67/32
    istio.io/rev: default
    kubectl.kubernetes.io/default-container: debug
    kubectl.kubernetes.io/default-logs-container: debug
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"first-ml:/Pod:asif-test/model-debug"},"name":"model-debug","namespace":"asif-test"},"spec":{"containers":[{"command":["sleep","3600"],"image":"python:3.11-slim","name":"debug","volumeMounts":[{"mountPath":"/mnt/models","name":"diabetes-model-volume"}]}],"volumes":[{"name":"diabetes-model-volume","persistentVolumeClaim":{"claimName":"diabetes-model-pvc"}}]}}
    sidecar.istio.io/interceptionMode: REDIRECT
    sidecar.istio.io/status: '{"initContainers":["istio-validation","istio-proxy"],"containers":null,"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert","istio-ca-crl"],"imagePullSecrets":null,"revision":"default"}'
    traffic.sidecar.istio.io/excludeInboundPorts: "15020"
    traffic.sidecar.istio.io/includeInboundPorts: '*'
    traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
  creationTimestamp: "2025-12-04T23:04:14Z"
  generation: 1
  labels:
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: model-debug
    service.istio.io/canonical-revision: latest
  name: model-debug
  namespace: asif-test
  resourceVersion: "120851499"
  uid: c04f9ee3-54bc-4090-aa9d-801bf0f8cac9
spec:
  containers:
  - command:
    - sleep
    - "3600"
    env:
    - name: KUBERNETES_SERVICE_HOST
      value: api.c-321a6c0.kyma-stage.internal.live.k8s.ondemand.com
    image: python:3.11-slim
    imagePullPolicy: IfNotPresent
    name: debug
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/models
      name: diabetes-model-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t4snf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,15020
    - --log_output_level=all:warn
    - --run-validation
    - --skip-rule-apply
    env:
    - name: BOOTSTRAP_XDS_AGENT
      value: "true"
    - name: CITADEL_SELF_SIGNED_CA_RSA_KEY_SIZE
      value: "4096"
    - name: WORKLOAD_RSA_KEY_SIZE
      value: "3072"
    image: europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2:1.27.1-distroless
    imagePullPolicy: IfNotPresent
    name: istio-validation
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 192Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t4snf
      readOnly: true
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=all:warn
    env:
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: ISTIO_CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.cpu
    - name: PROXY_CONFIG
      value: |
        {"tracingServiceName":"CANONICAL_NAME_ONLY","proxyMetadata":{"BOOTSTRAP_XDS_AGENT":"true","CITADEL_SELF_SIGNED_CA_RSA_KEY_SIZE":"4096","WORKLOAD_RSA_KEY_SIZE":"3072"},"holdApplicationUntilProxyStarts":true}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: debug
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.cpu
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: model-debug
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/v1/namespaces/asif-test/pods/model-debug
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    - name: BOOTSTRAP_XDS_AGENT
      value: "true"
    - name: CITADEL_SELF_SIGNED_CA_RSA_KEY_SIZE
      value: "4096"
    - name: WORKLOAD_RSA_KEY_SIZE
      value: "3072"
    image: europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2:1.27.1-distroless
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - pilot-agent
          - request
          - --debug-port=15020
          - POST
          - drain
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 14
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 192Mi
    restartPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    startupProbe:
      failureThreshold: 600
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 3
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/run/secrets/istio/crl
      name: istio-ca-crl
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t4snf
      readOnly: true
  nodeName: ip-10-250-74-114.eu-central-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workload-socket
  - emptyDir: {}
    name: credential-socket
  - emptyDir: {}
    name: workload-certs
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - configMap:
      defaultMode: 420
      name: istio-ca-crl
      optional: true
    name: istio-ca-crl
  - name: diabetes-model-volume
    persistentVolumeClaim:
      claimName: diabetes-model-pvc
  - name: kube-api-access-t4snf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T23:04:19Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T23:04:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-12-08T17:05:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-12-08T17:05:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T23:04:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://818000503f115efe2e10d01f9d7eba946ca3a53a1fff32c26cabc7e73b1d9701
    image: docker.io/library/python:3.11-slim
    imageID: docker.io/library/python@sha256:193fdd0bbcb3d2ae612bd6cc3548d2f7c78d65b549fcaa8af75624c47474444d
    lastState:
      terminated:
        containerID: containerd://f11df43009cc18020c4c0c28a5303f3f1951349e5485799f18edbfd747c10f4f
        exitCode: 0
        finishedAt: "2025-12-08T17:05:07Z"
        reason: Completed
        startedAt: "2025-12-08T16:05:07Z"
    name: debug
    ready: true
    resources: {}
    restartCount: 90
    started: true
    state:
      running:
        startedAt: "2025-12-08T17:05:07Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /mnt/models
      name: diabetes-model-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t4snf
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.250.74.114
  hostIPs:
  - ip: 10.250.74.114
  initContainerStatuses:
  - allocatedResources:
      cpu: 10m
      memory: 192Mi
    containerID: containerd://e6b00b340f9342327f99fee52685e11c9e892935c23a72b8a668d8cbd1a0a38c
    image: europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2:1.27.1-distroless
    imageID: europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2@sha256:31e4635f0ec3af87bd185e8d869d17ebd2de13d5d94634a517f6f659d1d49b59
    lastState: {}
    name: istio-validation
    ready: true
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 192Mi
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://e6b00b340f9342327f99fee52685e11c9e892935c23a72b8a668d8cbd1a0a38c
        exitCode: 0
        finishedAt: "2025-12-04T23:04:19Z"
        reason: Completed
        startedAt: "2025-12-04T23:04:19Z"
    user:
      linux:
        gid: 1337
        supplementalGroups:
        - 1337
        uid: 1337
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t4snf
      readOnly: true
      recursiveReadOnly: Disabled
  - allocatedResources:
      cpu: 10m
      memory: 192Mi
    containerID: containerd://0a91469200c02c798ddfec3daa479e1d12213a56e47bb4903610bc09f5c763d1
    image: europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2:1.27.1-distroless
    imageID: europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2@sha256:31e4635f0ec3af87bd185e8d869d17ebd2de13d5d94634a517f6f659d1d49b59
    lastState: {}
    name: istio-proxy
    ready: true
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 192Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-12-04T23:04:19Z"
    user:
      linux:
        gid: 1337
        supplementalGroups:
        - 1337
        uid: 1337
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/run/secrets/istio/crl
      name: istio-ca-crl
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-t4snf
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Running
  podIP: 10.96.3.67
  podIPs:
  - ip: 10.96.3.67
  qosClass: Burstable
  startTime: "2025-12-04T23:04:14Z"
