apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mlflow-rwx  
  resources:
    requests:
      storage: 20Gi    