apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-shared-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mlflow-rwx